[Interface]
# Bouncing = 0
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = yOnslzzpLhKjMxph+bLGMsSVOji0diIIyIBI0jTWSUs=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# CA-FREE#33
PublicKey = JB84ctFi3l+gxJxr/kwYXlKwLcmqWxuuLBkpE1anmgo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 195.242.214.194:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a0d:5600:19:41::10]:51820
PersistentKeepalive = 25