[Interface]
# Bouncing = 0
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = oCggE2aZY4x7wKygwoO1jkbatWMfuqJsgJnwgPJxs00=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# CA-FREE#30
PublicKey = CDPzpwQ2oQuV6ImkpVkQ3OUzV1BDrvNLKqqtewqeFk4=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 195.242.214.146:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a0d:5600:19:37::10]:51820
PersistentKeepalive = 25