[Interface]
# Bouncing = 1
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = sIMWCDvMM48n7uYxN/XJ9/Pct1YKQxjNweOs62piTkU=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# JP-FREE#18
PublicKey = 9Yy7/zeaFvKd/ETcLg0PvsJb5PVMj9dX4Wg7NVNVbCs=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.88.103.48:51820

PersistentKeepalive = 25